---
- name: Install the build
  apt:
    name: "{{ build_package}}"
    state: present

- name: Download source redis
  get_url: url=http://download.redis.io/releases/{{ redis_source_name }} dest=/tmp

- name: Unrar file
  unarchive:
    copy: no
    dest: /tmp/
    src: /tmp/{{ redis_source_name }}
- name: make file and install
  shell: cd /tmp/{{ redis_version }} && make && make install

- name: Create Redis User Group and Dir
  command: "adduser --system --group --no-create-home redis"

- name: Make a directory
  file:
    path: /etc/redis
    state: directory
    owner: redis
    group: redis
    mode: 0775

- name: Make log directory
  file:
    path: /var/log/redis
    state: directory
    owner: redis
    group: redis
    mode: 0775

- name: Make file systemd
  template:
    src: redis.service
    dest: /etc/systemd/system/

- name: Set ownership and permission
  file:
    path: /var/lib/redis
    state: directory
    owner: redis
    group: redis
    mode: 0775

- name: Set overcommit_memory and net.core.somaxcon in /etc/sysctl.conf
  blockinfile:
    path: /etc/sysctl.conf
    state: present
    insertbefore: EOF
    block: |
      vm.overcommit_memory=1
      net.core.somaxconn=65535
  register: modify_kernel

- name: Reboot machine
  reboot:
  when: modify_kernel.changed

- name: Configure Redis and restart service.
  template:
    src: "redis.conf"
    dest: "{{ redis_conf_path }}"
    mode: 0644
  notify: restart redis
        
- name: Clean up build dependencies
  apt:
    name: "{{ build_package}}"
    state: absent
- name: Check service Redis and enabled on boot.
  service: 
    name: "{{ redis_daemon }}"
    state: started
    enabled: yes

