---
- name: Install the build
  apt:
    name: "{{ build_package}}"
    state: present

- name: Download source redis
  get_url: url=http://download.redis.io/releases/{{ redis_version }}.tar.gz dest=/tmp

- name: Unrar file
  unarchive:
    copy: no
    dest: /tmp/
    src: /tmp/{{ redis_version }}.tar.gz
- name: make file and install
  shell: cd /tmp/{{ redis_version }} && make && make install

- name: Create Redis User Group and Dir
  command: "adduser --system --group --no-create-home redis"

- name: Make a directory
  file:
    path: /etc/redis
    state: directory
    owner: redis
    group: redis
    mode: 0775

- name: Make log directory
  file:
    path: /var/log/redis
    state: directory
    owner: redis
    group: redis
    mode: 0775

- name: Make file systemd
  template:
    src: redis.service
    dest: /etc/systemd/system/

- name: Set ownership and permission
  file:
    path: /var/lib/redis
    state: directory
    owner: redis
    group: redis
    mode: 0775

- name: Increase Overcommit_memory
  sysctl:
    name: vm.overcommit_memory
    value: 1
    state: present
    reload: yes

- name: Increase SoMaxConn
  sysctl:
    name: net.core.somaxconn
    value: 65535
    state: present
    reload: yes

- name: Configure Redis and restart service.
  template:
    src: "redis.conf"
    dest: "{{ redis_conf_path }}"
    mode: 0644
  notify: restart redis

- name: Make logrotate directory
  file:
    path: /etc/logrotate.d
    state: directory

- name: Configure logrotate
  template:
    src: "{{ redis_logrotate_conf_template }}"
    dest: "/etc/logrotate.d/redis_logrotate.conf"
        
- name: Clean up build dependencies
  apt:
    name: "{{ build_package}}"
    state: absent
- name: Check service Redis and enabled on boot.
  service: 
    name: "{{ redis_daemon }}"
    state: started
    enabled: yes

